<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Customer\Module'                        => __DIR__ . '/Module.php',
    'Customer\Controller\IndexController' => __DIR__ . '/src/Customer/Controller/IndexController.php',
    'CustomerTest\Framework\TestCase'        => __DIR__ . '/tests/Customer/Framework/TestCase.php',
    'CustomerTest\SampleTest'                => __DIR__ . '/tests/Customer/SampleTest.php',
);
