CREATE TABLE IF NOT EXISTS `quser` (
  `USERID` int(11) NOT NULL AUTO_INCREMENT,  
  `UNAME` varchar(50) CHARACTER SET utf8 NOT NULL,
  `UNICKNAME` varchar(50) CHARACTER SET utf8 NOT NULL,
  `UHEAD` varchar(50) CHARACTER SET utf8 DEFAULT NULL,
  `UAGE` INT DEFAULT NULL,
  `UHOBBIES` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  `UPLACE` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  `UCOMMENT` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  `UTIME` DATE DEFAULT NULL,
  `UBRAND` varchar(50) CHARACTER SET utf8 DEFAULT NULL,
  `UPASS` varchar(112) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `USEX` INT CHARACTER SET utf8 DEFAULT '1',
  PRIMARY KEY (`USERID`)
) ENGINE=MyISAM  DEFAULT CHARSET=gbk AUTO_INCREMENT=42 ;

INSERT INTO `quser` (`USERID`, `UNAME`, 'UNICKNAME',`UHEAD`, `UAGE`, `UHOBBIES`, `UPLACE`, `UEXPLAIN`, `UTIME`, `UBRAND`, `UPASS`, `USEX`) VALUES
(1, '昵称测试1, 'admin','a1.jpg', '18', '篮球 羽毛球', '烟台', '❥、Ｈandsome在这里铸就,ｋing在这里诞生', '2014-05-16', NULL, 'admin', '1'),